version: '3'

vars:
  INPUT: '{{.INPUT | default "src/sample/index.tex"}}'
  OUTPUT: '`echo $(basename "$(dirname "{{.INPUT}}")")`'
  DOCKER_COMPOSE: "docker-compose"
  UP: "{{.DOCKER_COMPOSE}} --remove-orphans up"
  OUTPUT_DIRECTORY: build
  LATEXMK_ARGS: "-shell-escape -interaction=nonstopmode -file-line-error -output-directory={{.OUTPUT_DIRECTORY}}"
  TEXINPUTS: "{{.TASKFILE_DIR}}:{{.OUTPUT_DIRECTORY}}:src/ec/style"
  RUN: "{{.DOCKER_COMPOSE}} run -e TEXINPUTS={{.TEXINPUTS}} texlive"
  LATEXMK_COMMAND: "{{.RUN}} latexmk {{.LATEXMK_ARGS}}"

tasks:
  default:
    deps: [fresh]

  build:
    cmds:
      - "{{.LATEXMK_COMMAND}} -jobname={{.OUTPUT}} {{.INPUT}}"
      - task: chmodbuild

  clean:
    cmds:
      - "{{.RUN}} rm -rf build"

  chmodbuild:
    cmds:
      - "{{.RUN}} chmod 777 build"

  lint:
    cmds:
      - "{{.RUN}} chktex {{.INPUT}}"
      - "{{.RUN}} lacheck {{.INPUT}}"

  fresh:
    deps: [clean, build]

  watch:
    cmds:
      - "{{.LATEXMK_COMMAND}} -pvc -jobname={{.OUTPUT}} {{.INPUT}}"
      - task: chmodbuild
